//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarrierAPI_Test_Cases.CarrierAPIXML {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CarrierAPIXML.ICarrierAPIXML")]
    public interface ICarrierAPIXML {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarrierAPIXML/PerformShipping", ReplyAction="http://tempuri.org/ICarrierAPIXML/PerformShippingResponse")]
        string PerformShipping(int serviceUsed, int serviceID, double width, double height, double length, double weight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarrierAPIXML/PerformShipping", ReplyAction="http://tempuri.org/ICarrierAPIXML/PerformShippingResponse")]
        System.Threading.Tasks.Task<string> PerformShippingAsync(int serviceUsed, int serviceID, double width, double height, double length, double weight);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICarrierAPIXMLChannel : CarrierAPI_Test_Cases.CarrierAPIXML.ICarrierAPIXML, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CarrierAPIXMLClient : System.ServiceModel.ClientBase<CarrierAPI_Test_Cases.CarrierAPIXML.ICarrierAPIXML>, CarrierAPI_Test_Cases.CarrierAPIXML.ICarrierAPIXML {
        
        public CarrierAPIXMLClient() {
        }
        
        public CarrierAPIXMLClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CarrierAPIXMLClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarrierAPIXMLClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarrierAPIXMLClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string PerformShipping(int serviceUsed, int serviceID, double width, double height, double length, double weight) {
            return base.Channel.PerformShipping(serviceUsed, serviceID, width, height, length, weight);
        }
        
        public System.Threading.Tasks.Task<string> PerformShippingAsync(int serviceUsed, int serviceID, double width, double height, double length, double weight) {
            return base.Channel.PerformShippingAsync(serviceUsed, serviceID, width, height, length, weight);
        }
    }
}
