//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarrierAPI.LoggingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoggingService.ILoggingService")]
    public interface ILoggingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoggingService/LogSuccess", ReplyAction="http://tempuri.org/ILoggingService/LogSuccessResponse")]
        void LogSuccess(string successMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoggingService/LogSuccess", ReplyAction="http://tempuri.org/ILoggingService/LogSuccessResponse")]
        System.Threading.Tasks.Task LogSuccessAsync(string successMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoggingService/LogFailure", ReplyAction="http://tempuri.org/ILoggingService/LogFailureResponse")]
        void LogFailure(string errorMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoggingService/LogFailure", ReplyAction="http://tempuri.org/ILoggingService/LogFailureResponse")]
        System.Threading.Tasks.Task LogFailureAsync(string errorMessage);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoggingServiceChannel : LoggingService.ILoggingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoggingServiceClient : System.ServiceModel.ClientBase<LoggingService.ILoggingService>, LoggingService.ILoggingService {
        
        public LoggingServiceClient() {
        }
        
        public LoggingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoggingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoggingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoggingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void LogSuccess(string successMessage) {
            base.Channel.LogSuccess(successMessage);
        }
        
        public System.Threading.Tasks.Task LogSuccessAsync(string successMessage) {
            return base.Channel.LogSuccessAsync(successMessage);
        }
        
        public void LogFailure(string errorMessage) {
            base.Channel.LogFailure(errorMessage);
        }
        
        public System.Threading.Tasks.Task LogFailureAsync(string errorMessage) {
            return base.Channel.LogFailureAsync(errorMessage);
        }
    }
}
